### ISSUE TITLE
Cyrillic is dead

### ISSUE THREAD

**Issue by erxson** [jpenilla/better-fabric-console#15]
![image](https://user-images.githubusercontent.com/50082485/210382719-6c872130-bf04-4452-bb39-7f37d78b97a6.png)

**Comment by jpenilla** [comment]
I can't seem to reproduce any issues on my mac running macOS Ventura with iTerm, only using fabric api and bfc.

<img width="1580" alt="Screenshot 2023-01-03 at 1 17 30 PM" src="https://user-images.githubusercontent.com/11360596/210442856-3b70b0c4-efef-48d5-84c7-8dbda4d3c4cb.png">
<img width="647" alt="Screenshot 2023-01-03 at 1 17 55 PM" src="https://user-images.githubusercontent.com/11360596/210442912-93809e38-5638-4f6c-81d3-1329bd629ee2.png">
