### ISSUE TITLE
NotEnoughCrashes incompatibility

### ISSUE THREAD

**Issue by davidalb97** [jpenilla/better-fabric-console#2]
Using the mod in conjunction with NotEnoughCrashes mod incapacitates better fabric console's ability to suppress the vanilla console, causing duplicated console output.

Modlist:
- `fabric@0.42.1+1.17`
- `better-fabric-console@1.0.0-SNAPSHOT`
- `fabric@0.42.1+1.17`
- `fabricloader@0.11.7`
- `notenoughcrashes@3.7.2+1.17.1`

Java 17, MC 1.17.1

NotEnoughCrashes curseforge: https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes
NotEnoughCrashes modrinth: https://modrinth.com/mod/notenoughcrashes
NotEnoughCrashes github: https://github.com/natanfudge/not-enough-crashes

**Comment by jpenilla** [comment]
I'm unsure what the use of NotEnoughCrashes is when better-fabric-console has it's own remapper built in... there used to be NEC compatibly code which I ripped out when adding my own stacktrace/logger name remapper.
