### ISSUE TITLE
Allow project distribution

### ISSUE THREAD

**Issue by BUBUSTEIN13** [jpenilla/better-fabric-console#20]
Allow project distribution because I wanna use it on my server. My host said that I can't add this mod because the Dev doesn't allow project distribution.

**Comment by jpenilla** [comment]
Not sure what you mean, the MIT license is quite permissive in regard to distribution

**Comment by BUBUSTEIN13** [comment]
In the License tab you need to check the first thing: 
![image](https://user-images.githubusercontent.com/84980561/218330038-46695065-a425-4913-aed3-5866a905ad96.png)

**Comment by BUBUSTEIN13** [comment]
![image](https://user-images.githubusercontent.com/84980561/218330117-e5c88a5c-5489-4f00-baa4-26631f3e883a.png)

**Comment by jpenilla** [comment]
What host is this? And what other platforms do they support? I'm more inclined to put this on Modrinth than to deal with curseforge

**Comment by BUBUSTEIN13** [comment]
Aternos host

They support Curseforge and Modrinth

**Comment by jpenilla** [comment]
Will be here once it's reviewed by Modrinth https://modrinth.com/mod/better-fabric-console
