### ISSUE TITLE
Add message filtering

### ISSUE THREAD

**Issue by Prunkles** [jpenilla/better-fabric-console#23]
When `log-player-executed-commands` is true, every command a player type is visible in the console. Including messages that may contain sensitive information.

I guess filtering messages with a regex in the config will fix this problem.

**Comment by jpenilla** [comment]
Commands are not a secure entry form regardless of if they are logged. I'm not really convinced this is worth adding.

Some more context: the command logging feature is ported from Paper where it is also a simple on/off.

If you really want to filter your logs, you can use a custom log4j config.
