### ISSUE TITLE
Add Fabric API as a dependency on Modrinth

### ISSUE THREAD

**Issue by Broyojo** [jpenilla/better-fabric-console#25]
Since better-fabric-console depends on Fabric API, it would be nice if this was shown on Modrinth so that not only people could see that they needed to download the mod, but automatic mod downloading tools like [ferium](https://github.com/gorilla-devs/ferium) could automatically download Fabric API along with better-fabric-console.

**Comment by jpenilla** [comment]
Done with 1.1.6
