### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Nivirog** [jpenilla/better-fabric-console#26]
---- Minecraft Crash Report ----
// My bad.

Time: 2023-08-02 15:21:19
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
	at net.minecraft.server.dedicated.DedicatedServer.sendSystemMessage(DedicatedServer.java:1181)
	at net.minecraft.server.players.PlayerList.broadcastSystemMessage(PlayerList.java:809)
	at net.minecraft.server.players.PlayerList.broadcastSystemMessage(PlayerList.java:805)
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:236)
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:131)
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:118)
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.redirect$bda000$fabric-networking-api-v1$handlePlayerJoin(ServerLoginPacketListenerImpl.java:563)
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:68)
	at net.minecraft.network.Connection.tick(Connection.java:259)
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:172)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:908)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:283)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:265)
	at java.base@17.0.6/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.6, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 917328528 bytes (874 MiB) / 2252341248 bytes (2148 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
	Identifier: Intel64 Family 6 Model 140 Stepping 1
	Microarchitecture: Tiger Lake
	Frequency (GHz): 3.30
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9a49
	Graphics card #0 versionInfo: DriverVersion=31.0.101.3413
	Graphics card #1 name: NVIDIA GeForce RTX 3050 Ti Laptop GPU
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x25a0
	Graphics card #1 versionInfo: DriverVersion=31.0.15.3667
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 19554.18
	Virtual memory used (MB): 16301.78
	Swap memory total (MB): 3478.85
	Swap memory used (MB): 618.45
	JVM Flags: 1 total; -Xmx8G
	Fabric Mods: 
		additionaladditions: Additional Additions 6.0.0
			libgui: LibGui 8.0.1+1.20
				jankson: Jankson 5.0.1+j1.2.2
				libninepatch: LibNinePatch 1.2.0
		adorn: Adorn 5.0.0+1.20.1
		architectury: Architectury 9.1.12
		athena: Athena 3.0.0
		autoafk: Auto AFK 1.2.4
		bakery: Bakery 1.1.1
		balm-fabric: Balm 7.0.7
		beautify: Beautify 1.0.0+1.20
		benched: Benched 1.2.2+a
		better-fabric-console: Better Fabric Console 1.1.5
			adventure-platform-fabric: adventure-platform-fabric 5.10.0-SNAPSHOT
				net_kyori_adventure-api: adventure-api 4.14.0
				net_kyori_adventure-key: adventure-key 4.14.0
				net_kyori_adventure-platform-api: adventure-platform-api 4.3.0
				net_kyori_adventure-text-logger-slf4j: adventure-text-logger-slf4j 4.14.0
				net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.14.0
				net_kyori_adventure-text-serializer-ansi: adventure-text-serializer-ansi 4.14.0
				net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.14.0
				net_kyori_adventure-text-serializer-json: adventure-text-serializer-json 4.14.0
				net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.14.0
				net_kyori_ansi: ansi 1.0.1
				net_kyori_examination-api: examination-api 1.3.0
				net_kyori_examination-string: examination-string 1.3.0
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			net_fabricmc_mapping-io: mapping-io 0.4.2
			org_fusesource_jansi_jansi: jansi 2.4.0
			org_jline_jline: jline 3.21.0
			org_jline_jline-terminal-jansi: jline-terminal-jansi 3.21.0
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		betterarcheology: Better Archeology 1.0.2
		bewitchment: Bewitchment 1.20-4
			impersonate: Impersonate 2.10.0
			midnightlib: MidnightLib 1.4.1
			playerabilitylib: Pal 1.8.0
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			step-height-entity-attribute: Step Height Entity Attribute 1.2.0
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		biomemakeover: Biome Makeover 1.20.1-1.10.2
			taniwha: Taniwha 1.20.0-5.1.1
		bookshelf: Bookshelf 20.0.2
		botanypots: BotanyPots 13.0.2
		botanytrees: BotanyTrees 9.0.2
		bushierflowers: Bushier Flowers 0.0.3-1.20.1
		candlelight: Candlelight 1.2.2
		chipped: Chipped 3.0.1
		chunky: Chunky 1.3.92
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		clutter: Clutter 1.20.1-0.3.9
		companion: Companion 5.0.2
		connectedglass: Connected Glass 1.1.7
		couplings: Couplings 1.9.5+1.20
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		creeperoverhaul: Creeper Overhaul 3.0.1
		croptopia: Croptopia 2.3.2
		ctov: ChoiceTheorem's Overhauled Village 3.3.3
		doapi: Lets Do Api 1.2.5
		easyanvils: Easy Anvils 8.0.1
		emi: EMI 1.0.17+1.20.1+fabric
		emi_loot: EMI Loot 0.6.5+1.20.1
		ends_delight: End's Delight 1.0
		exlinefurniture: Exline's Furniture 2.6.1
		expandeddelight: Expanded Delight 0.3.0.2
		fabric-api: Fabric API 0.86.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.62+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.1+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.52+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.9+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.49+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.19+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.1+4df89eb277
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.28+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.8+kotlin.1.9.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		fabrictailor: Fabric Tailor 2.1.2
			config2brigadier: Config to Brigadier 1.2.3
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		fallingtree: FallingTree 4.2.4
		farmersdelight: Farmer's Delight 1.20.1-1.4.1
		fennecfox: Fennec Fox 1.0.0
		forgeconfigapiport: Forge Config API Port 8.0.0
		friendsandfoes: Friends&Foes 1.9.3
		geckolib: Geckolib 4.2.1
			com_eliotlash_mclib_mclib: mclib 20
		geophilic: Geophilic v2.0.0-mc1.20u1.20.1
		gravestones: Gravestones v1.15
		handcrafted: Handcrafted 2.3.2
		harvestwithease: Harvest with ease 7.0.0.2
		iceberg: Iceberg 1.1.13
		immersive_paintings: Immersive Paintings 0.6.1+1.20.1
		imst: Immersive structures 2.1.0
		inventorysorter: Inventory Sorter 1.9.0-1.20
			kyrptconfig: Kyrpt Config 1.5.6-1.20
		jade: Jade 11.4.0
		java: OpenJDK 64-Bit Server VM 17
		jmi: JourneyMapIntegration 1.20.1-0.14-45
		journeymap: Journeymap 5.9.12
			journeymap-api-fabric: JourneyMap API 1.20-1.9-fabric-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.11.2
		mcwbridges: Macaw's Bridges 2.1.0
		mcwdoors: Macaw's Doors 1.1.0
		mcwfences: Macaw's Fences and Walls 1.0.7
		mcwlights: Macaw's Lights and Lamps 1.0.6
		mcwpaths: Macaw's Paths and Pavings 1.0.3
		mcwroofs: Macaw's Roofs 2.2.4
		mcwtrpdoors: Macaw's Trapdoors 1.1.1
		minecraft: Minecraft 1.20.1
		modernfix: ModernFix 5.4.2+mc1.20.1
		moonlight: Moonlight 1.20-2.7.2
		moremobvariants: More Mob Variants 1.2.2
		mr_ctov_beautifycompat: CTOV - Beautify Compat 2.0
		mr_ctov_farmersdelightcompat: CTOV - Farmer Delight Compat 2.0
		mr_ctov_friendsandfoescompat: CTOV - Friends and Foes Compat 2.0
		njb: Not Just Biomes 1.1.0
		patchouli: Patchouli 1.20.1-81-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.7.7+1.14.4-1.20.1
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		philipsruins: Philip`s Ruins 1.20.1
		polymorph: Polymorph 0.49.0+1.20.1
			cardinal-components-base: Cardinal Components API (base) 5.2.1
			cardinal-components-block: Cardinal Components API (blocks) 5.2.1
			cardinal-components-entity: Cardinal Components API (entities) 5.2.1
			cardinal-components-item: Cardinal Components API (items) 5.2.1
			spectrelib: SpectreLib 0.13.13+1.20.1
		puzzleslib: Puzzles Lib 8.0.15
		recipe-book-delight: Recipe Book Delight 0.1.1-1.20
			dark-matter-base: Dark Matter Base 0.6.1-1.20
			dark-matter-enums: Dark Matter Enums 0.6.1-1.20
			dark-matter-minecraft: Dark Matter Minecraft 0.6.1-1.20
			dark-matter-recipe-book: Dark Matter Recipe Book 0.6.1-1.20
		repurposed_structures: Repurposed Structures 7.0.0+1.20-fabric
		resourcefulconfig: Resourcefulconfig 2.0.0
		resourcefullib: Resourceful Lib 2.1.8
			com_teamresourceful_bytecodecs: bytecodecs 1.0.1
			com_teamresourceful_yabn: yabn 1.0.3
		sit: Sit 1.20-24
		snifferplus: Hellion's Sniffer+ 0.2.0
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.7
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.12+b
		supplementaries: Supplementaries 1.20-2.5.21
		swampier_swamps: Swampier Swamps 1.20-4.0.0
		tectonic: Tectonic 2.1
		terrestria: Terrestria 6.0.9
			biolith: Biolith 1.0.0-alpha.8
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 7.0.1
			terraform-config-api-v1: Terraform Config API (v1) 7.0.1
			terraform-dirt-api-v1: Terraform Dirt API (v1) 7.0.1
			terraform-shapes-api-v1: Terraform Shapes API (v1) 7.0.1
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 7.0.1
			terraform-tree-api-v1: Terraform Tree API (v1) 7.0.1
			terrestria-common: Terrestria: Common 6.0.9
			terrestria-worldgen: Terrestria: World Generation 6.0.9
		trashslot: TrashSlot 15.0.0
		trinkets: Trinkets 3.7.1
		twigs: Twigs 3.1.0
		ubesdelight: Ube's Delight 0.1.3
		umu_backpack: UMU Backpack 5.1
			mm: Manningham Mills 2.3
			umu_config: UMU Config 0.0-beta.0
		vinery: Vinery 1.4.2
		waystones: Waystones 14.0.1
		wilderwild: Wilder Wild 2.1.1-Fabric+1.20.1
			frozenlib: FrozenLib 1.3.4-Fabric+1.20.1
				blue_endless_jankson: jankson 1.2.2
				com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.9
			nbtcrafting: NBT Crafting 2.2.3+mc1.20
		ydms_redpanda: YDM's Red Panda 1.0.4
	Server Running: true
	Player Count: 0 / 20; []
	Data Packs: vanilla, Supplementaries Generated Pack, fabric, tectonic:tectonic
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by jpenilla** [comment]
Can you try with this build https://github.com/jpenilla/better-fabric-console/suites/14335211345/artifacts/806859599 ?

**Comment by Nivirog** [comment]
Yep, everything good, thx
