### ISSUE TITLE
net.kyori.adventure causing Exception in server tick loop when player enter the server

### ISSUE THREAD

**Issue by aeaver** [jpenilla/better-fabric-console#27]
_**Version:**_

Minecraft version: 1.20.1
Fabric mod loader version: 0.14.22

**fabric api:**
fabric-api-0.51.1+1.20.1.jar

**better fabric console version:**
better-fabric-console-mc1.20.1-1.1.6

**_Issue:_**

when a player join the server the server will shut down and user will get messege disconnected

https://mclo.gs/3vfVSrG

![image](https://github.com/jpenilla/better-fabric-console/assets/121331578/793c43e3-cf8b-49dd-a459-982a82d23e05)

**Comment by jpenilla** [comment]
Seems like some sort of mod conflict, I'm unable to reproduce this with just better-fabric-console and fabric-api.

For me to look further into this, I would need to know what specific mod is conflicting. I don't have time to sort through and test all 300 that you are using myself. [This guide](https://docs.papermc.io/paper/basic-troubleshooting#binary-search) might be helpful in finding the culprit.

**Comment by aeaver** [comment]
yeah it was a mod conflict with wilder wild 2.1.2

**Comment by zml2008** [comment]
https://github.com/FrozenBlock/WilderWild/blob/2.1.2-mc1.20.1/src/main/java/net/frozenblock/wilderwild/misc/WilderSharedConstants.java

This class is loaded from the Mixin config plugin, and is triggering a classload of the `Component` class during the mixin prepare phase. This causes it to be loaded too early so our mixins are not applied. The config plugin booleans should be stored in their own class isolated from everything else to avoid this issue.

From debugger output:
<img width="1012" alt="debugger output paused on a breakpoint within the Mixin transformer" src="https://github.com/jpenilla/better-fabric-console/assets/629092/d576b500-9738-4cdd-b592-aaf6d5c6bbf8">
