### ISSUE TITLE
Where can I find the jar file?

### ISSUE THREAD

**Issue by WieeRd** [jpenilla/better-fabric-console#3]
Fabric's default console does lack functionalities, and this reallys looks useful.  
But where can I find the .jar file? Couldn't find the name "better fabric console" anywhere on the interent other than this github page.  
Do I have to compile it myself?

**Comment by jpenilla** [comment]
The jar is published to GH actions, I'll go ahead and put it on curseforge though.

**Comment by jpenilla** [comment]
https://www.curseforge.com/minecraft/mc-mods/better-fabric-console will be here once approved
