### ISSUE TITLE
Server Crashes at Startup (BFC 1.18.1-1.0.0)

### ISSUE THREAD

**Issue by Toilet-Man** [jpenilla/better-fabric-console#4]
Same thing happens with **better-fabric-console-mc1.18.2-1.0.2**, just in case

I think it's an incompatibility with AdventureZ but I'm sure you're better than me to diagnose the problem

Here is the log:
[latest.log](https://github.com/jpenilla/better-fabric-console/files/8191204/latest.log)

Let me know if I can do anything <3
Thank you for checking out this issue

**Comment by jpenilla** [comment]
I highly doubt the same issue is present on 1.0.2, given the code referenced in the error doesn't exist in that version.

**Comment by cpm9** [comment]
Server crashing on startup for me too here is the latest.log file:

[latest.log](https://github.com/jpenilla/better-fabric-console/files/8201772/latest.log)

I was using better-fabric-console-mc1.18.1-1.0.0.jar

**Comment by jpenilla** [comment]
If this issue is still present in 1.0.2, please open a new issue with logs from 1.0.2.
