### ISSUE TITLE
Remove dependency on Fabric API

### ISSUE THREAD

**Issue by LoganDark** [jpenilla/better-fabric-console#5]
The only thing stopping this mod from completely superseding [mine](https://github.com/logandark/fabric-console) is the fact that it depends on Fabric API to use exactly one feature:

https://github.com/jpenilla/better-fabric-console/blob/d4272c56e8abcdb1052aca48785a379c5d24d21e/src/main/java/xyz/jpenilla/betterfabricconsole/BetterFabricConsole.java#L38

(Yes, that is the only line in the entire mod that uses Fabric API. The rest is all built into Fabric Loader.)

This should be trivial to remove.

**Comment by jpenilla** [comment]
> (Yes, that is the only line in the entire mod that uses Fabric API. The rest is all built into Fabric Loader.)

This isn't exactly correct, adventure-platform which is used by better-fabric-console depends on fabric-api: https://github.com/KyoriPowered/adventure-platform-fabric/blob/mc/1.18/src/main/resources/fabric.mod.yaml#L25.

While it may be technically possible to use adventure's api and serializers without platform-fabric, it's not something I'm interested in.

Regardless of that I don't see an issue with requiring fabric-api in general.

**Comment by LoganDark** [comment]
> adventure-platform

Oh, I didn't notice that. Interesting. Looking closer at adventure-platform it doesn't even use Fabric API that much either - although it does use it a bit more than this mod does.

> I don't see an issue with requiring fabric-api in general.

Fabric API tends to have side effects such as automatically adding new S2C packets that I don't want on a vanilla server.

---

I'd rather leave this open just in case some contributor wants to drive on by and open a couple PRs to fix this. That may even be me at some point if I get around to it.
