### ISSUE TITLE
Adding Compatibility with JLINE

### ISSUE THREAD

**Issue by suerion** [jpenilla/better-fabric-console#66]
Could you add some Compatibilitys with Jline colored Console lines?

After adding Better fabric Console, it does not Color any lines anymore.

https://github.com/chirs241097/jline4mcdsrv/issues/27
https://modrinth.com/mod/jline4mcdsrv

**Comment by jpenilla** [comment]
better-fabric-console is a fork of jline4mcdsrv, they will not be compatible

**Comment by suerion** [comment]
ah okey, then i will disable jline, :)
