### ISSUE TITLE
Incompatible with the Styled Chat

### ISSUE THREAD

**Issue by nikijaz** [jpenilla/better-fabric-console#9]
**[Styled Chat](https://modrinth.com/mod/styled-chat)**
**Logs:** https://mclo.gs/Is8bvrE

**Comment by nikijaz** [comment]
**Styled Chat:** v1.3.2
**Better Fabric Console:** v1.0.5

**Comment by nikijaz** [comment]
[#](https://github.com/Patbox/StyledChat/issues/24)

**Comment by nikijaz** [comment]
My conclusion is that the problem is in [this commit](https://github.com/jpenilla/better-fabric-console/commit/4033ca8f23d7ce16da9359fcd352b3f9361b262d).

**Comment by jpenilla** [comment]
No idea what's happening here, that commit doesn't touch anything relevant and if it's actually the cause it's probably a fabric bug of some sort. I don't touch registries at all, let alone the chat type registry. My only guess was maybe this https://github.com/jpenilla/better-fabric-console/blob/master/src/main/java/xyz/jpenilla/betterfabricconsole/BetterFabricConsole.java#L86 is loading the registry class too early, but removing it didn't make any difference in my testing.

**Comment by nikijaz** [comment]
The problem is not with the Better fabric Console
